# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(default='uploads/default.jpg', upload_to='uploads/foods')),
                ('qtc', models.IntegerField()),
            ],
        ),
    ]
