# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160621_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=10),
        ),
    ]
